# Generated by Django 3.2.16 on 2023-01-13 13:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/magazine-blog/image/upload/v1672740868/static/img/default-profile.8c3e2b017043.png', max_length=255, verbose_name='static/img'),
        ),
    ]
