# Generated by Django 3.2.16 on 2022-12-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20221227_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
