# Generated by Django 3.2.16 on 2022-12-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='about',
            new_name='bio',
        ),
    ]
