# Generated by Django 3.2.16 on 2023-01-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_auto_20221230_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
